language: node_js
node_js:
- "0.8"
- "0.10"
- "0.11"
- "0.12"
- "1.x"
- "2.x"
sudo: false
services:
  - redis-server
  - mongodb
  - memcached
script: "npm install bunyan && node ./test/express.js | bunyan"
