language: node_js
node_js:
- "0.10"
- "0.11"
- "0.12"
- "1"
- "2"
- "4"
services:
  - redis-server
  - mongodb
  - memcached
  - mysql
before_script:
  - mysql -e 'create database test;'
script: "sh ./run.sh"
